apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-staging
  namespace: staging
  labels:
    app: wp-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-staging
  template:
    metadata:
      labels:
        app: wp-staging
    spec:
      containers:
      - name: wp-staging
        image: starlord345/wp:latest
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: wp-staging-service
  namespace: staging
spec:
  selector:
    app: wp-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-staging-wp
  namespace: staging
spec:
  rules:
  - host: wp-staging.agylpradipta.xyz
    http:
      paths:
        - backend:
            serviceName: wp-staging-service
            servicePort: 80